// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CommentsCheckController from "./comments_check_controller.js"
application.register("comments-check", CommentsCheckController)

import DragController from "./drag_controller.js"
application.register("drag", DragController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import LikeController from "./like_controller.js"
application.register("like", LikeController)

import NestedFormController from "./nested_form_controller.js"
application.register("nested-form", NestedFormController)

import PhotoPreviewController from "./photo_preview_controller.js"
application.register("photo-preview", PhotoPreviewController)

import RefreshListController from "./refresh_list_controller.js"
application.register("refresh-list", RefreshListController)

import ResetFormController from "./reset_form_controller.js"
application.register("reset-form", ResetFormController)
